### ISSUE TITLE
ArchiveFiles task zips up too much

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/pipelines-javascript#2]
The `ArchiveFiles@2` task in `azure-pipelines.yml` zips up the whole repository including folders like `.git` and dev dependencies inside `node_modules`. This is typically not what you want. What would be the production-quality solution here?

**Comment by betooliveira79** [comment]
@letmaik this option not exists until the moment.

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
